### ISSUE TITLE
Add `.commands(command1,command2,command3)`

### ISSUE THREAD

**Issue by tsanyqudsi** [AgentEnder/cli-forge#1]
Hi, I'm tried your framework and I think it needs something like in the title. It helps when a dev needs to make the cli scalable.

**Comment by AgentEnder** [comment]
Hey @tsanyqudsi 👋 

That's not a bad idea. I can look into it. The typescript typings admittedly may get a bit more complex than they already are.

How did your experiments go? I haven't really talked about this outside of a with a few colleagues and stray links in blog posts, so from a curiosity POV I'd love more feedback.

**Comment by tsanyqudsi** [comment]
It's good, but needs few things here and there. But then again it's still `0.3.0`.

I can make few more suggestions in new separate issues if you want.

**Comment by AgentEnder** [comment]
Yeah, either a few new issues or open a discussion for generic feedback both work :) 

Appreciate the early lookover, this is likely "usable" as is, but would like to get closer to feature parity with yargs minus a few of the things I don't really think were necessary.
